//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACW_08346_541045_Client.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SayHello", ReplyAction="http://tempuri.org/IService1/SayHelloResponse")]
        string SayHello(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetPubKey", ReplyAction="http://tempuri.org/IService1/GetPubKeyResponse")]
        string GetPubKey();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SortTheseValues", ReplyAction="http://tempuri.org/IService1/SortTheseValuesResponse")]
        string SortTheseValues(int[] values);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DecryptMessage", ReplyAction="http://tempuri.org/IService1/DecryptMessageResponse")]
        void DecryptMessage(byte[] Encrypted);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Sha1Hash", ReplyAction="http://tempuri.org/IService1/Sha1HashResponse")]
        string Sha1Hash(string toHash);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Sha256Hash", ReplyAction="http://tempuri.org/IService1/Sha256HashResponse")]
        string Sha256Hash(string toHash);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SignData", ReplyAction="http://tempuri.org/IService1/SignDataResponse")]
        byte[] SignData(string signedData);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : ACW_08346_541045_Client.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<ACW_08346_541045_Client.ServiceReference1.IService1>, ACW_08346_541045_Client.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string SayHello(int value) {
            return base.Channel.SayHello(value);
        }
        
        public string GetPubKey() {
            return base.Channel.GetPubKey();
        }
        
        public string SortTheseValues(int[] values) {
            return base.Channel.SortTheseValues(values);
        }
        
        public void DecryptMessage(byte[] Encrypted) {
            base.Channel.DecryptMessage(Encrypted);
        }
        
        public string Sha1Hash(string toHash) {
            return base.Channel.Sha1Hash(toHash);
        }
        
        public string Sha256Hash(string toHash) {
            return base.Channel.Sha256Hash(toHash);
        }
        
        public byte[] SignData(string signedData) {
            return base.Channel.SignData(signedData);
        }
    }
}
